---

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_peerapi_data:/data
  peerapi:
    build:
      context: ./iedon-net-api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config/auth42-cred:/data/auth42-cred
      - ./config/config.js:/usr/src/app/config.js
      - /var/log/peerapi:/usr/src/app/logs
      # - /var/run/peerapi:/var/run/peerapi
    #ports:
    #  - "3000:3000/tcp"
    #  - "4222:4222/tcp"
